name: GitHub CI
on: 
  workflow_dispatch:

jobs:
  macos:
    name: Macos Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          sudo apt install -y git
          git clone https://github.com/sub-store-org/Sub-Store.git
      - name: Build
        run: docker run -it \
            --device /dev/kvm \
            -p 50922:10022 \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -e "DISPLAY=${DISPLAY:-:0.0}" \
            -e GENERATE_UNIQUE=true \
            -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
            sickcodes/docker-osx:ventura /bin/zsh -c "brew install node@16"
