name: build
on:
    workflow_dispatch:
jobs:
  windows_build:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
         python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Checkout
        run: |
          sudo apt install git wget -y
          git clone https://github.com/sub-store-org/Sub-Store.git
          wget https://github.com/sub-store-org/Sub-Store/releases/download/2.14.154/sub-store.bundle.js
      - name:  Package Release
        run: |
            npm install pkg -g
            pkg ./sub-store.bundle.js -t macos-node16-x86
            ls -l 
      # - name: Install dependencies
      #   run: |
      #     npm install -g pnpm
      #     npm install -g pkg
      #     cd Sub-Store/backend && pnpm i
      # - name: Build
      #   run: |
      #     cd Sub-Store/backend
      #     dir
      #     pnpm run build
      # - name: Bundle
      #   run: |
      #     cd Sub-Store/backend
      #     pnpm run bundle
      # - name:  Package Release
      #   run: |
      #     pkg ./Sub-Store/backend/dist/sub-store.bundle.js -t macos-node16-x86
      #     ls -l ./Sub-Store/backend/dist/
